# Site settings
title:       Krzysiek Szymczak blog
email:       krzysztof.piotr.szymczak@gmail.com
author:      John Otander
description: "This is my blog, and this is what I do."
baseurl:     "/blog"
url:         "https://szymczakk.github.io/"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
enable_contact_us: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id: 

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: szymczakk-blog

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: szymczakk
bitbucket_username:
stackoverflow_id: 4907665/rakaz
twitter_username: szymczakk
skype_username: szymczakk@live.com
steam_nickname: kichol1
google_plus_id:
linkedin_username: krzysztof-szymczak
angellist_username: krzysztof-szymczak
medium_id:
bitcoin_url:
paypal_url: 
# my paypal url: paypal.me/szymczakk
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

#translations
text:
  home: 'Strona główna'
  contact: 'Kontakt'
  pagination:
    newer: 'Nowszy'
    older: 'Starszy'
  share_buttons:
    text:         'PS. <br> Udostępnij ten post jeśli masz ochotę :)'
    facebook:     'Wrzuć na Facebooka'
    twitter:      'Wrzuć na Twittera'
    googleplus:   'Wrzuć na Google+'
    linkedin:     'Wrzuć na LinkedIn'
    digg:         'Wrzuć na Digg'
    tumblr:       'Wrzuć na Tumblr'
    reddit:       'Wrzuć na Reddit'
    stumbleupon:  'Wrzuć na StumbleUpon'
    hackernews:   'Wrzuć na Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'około minut czytania'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'wysyłanie..'
      sent:     'Wiadomość wysłana!'
      error:    'Błąd!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'pl_PL'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

#Default settings
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
